export type { TabLockContext, TabLockOptions, TabLockResult, TryTabLockOptions } from "./locks/tab-lock"
export { tryWithTabLock, withTabLock } from "./locks/tab-lock"
export type { LeadershipGate, LeadershipGateOptions, Tenure } from "./patterns/leadership-gate"
export { createLeadershipGate } from "./patterns/leadership-gate"
export type { LeadershipContext, LeadershipLoopOptions } from "./patterns/leadership-loop"
export { createLeadershipLoop } from "./patterns/leadership-loop"
export type { TtlDedupeCache, TtlDedupeCacheOptions } from "./primitives/ttl-dedupe"
export { createTtlDedupeCache } from "./primitives/ttl-dedupe"
export type { Logger } from "./kernel/logger"
